#!/usr/bin/env bash

CI_RED="1;31"
CI_GREEN="1;32"

CI_CPP_COMPILER="c++"
CI_CPP_STANDARD="-std=c++14"
CI_CPP_WARNINGS="-Wall -Wextra"
CI_CPP_DEBUG="-g -D_GLIBCXX_DEBUG"
CI_CPP_OPTIMISE="-O2 -static -lm"

function ci-ansi-col-escape {
	ARG_VALUES=$1
	echo "\033["$ARG_VALUES"m"
}
function ci-colored {
	ARG_COLOR=$1
	ARG_TEXT=$2
	printf $(ci-ansi-col-escape $ARG_COLOR)$ARG_TEXT
}

function ci-strip-cpp-ext {
	ARG=$1
	echo $(sed -r 's/\.cpp$//g' <<< $ARG)
}
function ci-build {
	ARG_SOURCE=$1
	$CI_CPP_COMPILER $CI_CPP_STANDARD $CI_CPP_WARNINGS $CI_CPP_DEBUG $ARG_SOURCE -o $(ci-strip-cpp-ext $ARG_SOURCE).e
}

CI_SUBCMD=$1
shift
ci-$CI_SUBCMD "$@"
