indent_style = "Block"
use_small_heuristics = "Default"
binop_separator = "Front"
combine_control_expr = true
# comment_width
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
# disable_all_formatting
# error_on_line_overflow
# error_on_unformatted
fn_args_density = "Tall"
brace_style = "SameLineWhere"
empty_item_single_line = true
fn_single_line = false
# where_single_line
force_explicit_abi = true
format_strings = true
hard_tabs = true
imports_indent = "Block"
imports_layout = "Horizontal"
merge_imports = true
match_block_trailing_comma = true
max_width = 180
merge_derives = true
force_multiline_blocks = false
newline_style = "Unix"
normalize_comments = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
report_todo = "Never"
report_fixme = "Never"
skip_children = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 0
spaces_around_ranges = false
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Compressed"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = false
match_arm_blocks = true
# write_mode
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
# required_version
# hide_parse_errors
# color
# unstable_features
# license_template_path
# ignore
